# Generated by Django 5.2.4 on 2025-07-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('authors', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(choices=[('soft', 'Soft Cover'), ('hard', 'Hard Cover')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('audio', 'Audio')], max_length=20)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.PositiveIntegerField()),
                ('publishing_year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_physical', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='edition_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='edition_covers/')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.edition')),
            ],
        ),
    ]
