# Generated by Django 5.2.4 on 2025-08-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='audio_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
