# Generated by Django 5.2.4 on 2026-08-20 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_subcategory_of_alter_book_audio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('signature_quote', models.TextField(blank=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('soft', 'Мягкая обложка'), ('hard', 'Твёрдая обложка'), ('ebook', 'Электронная книга'), ('audio', 'Аудиокнига')], default='soft', max_length=10)),
                ('cover', models.ImageField(upload_to='book_covers/')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('published_year', models.PositiveIntegerField(help_text='Год выпуска именно этого издания.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2100)])),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='book_files/')),
                ('audio_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['book', 'format'],
            },
        ),
        migrations.CreateModel(
            name='MoodboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moodboards/')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Порядок вывода в сетке.')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='bookimage',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='books_amount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_physical',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Цвет фона страницы книги, подобранный под обложку. Формат #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Ожидается HEX-цвет, например #1A2B3C.')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Краткое описание без спойлеров.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uz', "O'zbekcha"), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_year',
            field=models.PositiveIntegerField(help_text='Год первой публикации произведения.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author'), name='unique_book_author'),
        ),
        migrations.AddField(
            model_name='character',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='books.book'),
        ),
        migrations.AddField(
            model_name='edition',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.book'),
        ),
        migrations.AddField(
            model_name='moodboardimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodboard', to='books.book'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
