# Generated by Django 5.2.4 on 2026-08-20 10:48

import server.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_character_edition_moodboardimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='file',
            field=models.FileField(blank=True, null=True, storage=server.storages.ProtectedStorage(), upload_to='book_files/'),
        ),
    ]
