# Generated by Django 5.2.4 on 2026-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_edition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена до скидки. Должна быть больше текущей.', max_digits=10, null=True),
        ),
    ]
