# Generated by Django 5.2.4 on 2025-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
        ('books', '0002_category_subcategory_of_alter_book_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='books.book'),
        ),
    ]
