# Generated by Django 5.2.4 on 2025-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_avatar_remove_profile_favourites'),
        ('books', '0002_category_subcategory_of_alter_book_audio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='books.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reads',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_by', to='books.book'),
        ),
    ]
