# Generated by Django 5.2.4 on 2025-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_favourites_profile_reads'),
        ('books', '0002_category_subcategory_of_alter_book_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='books.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reads',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='books.book'),
        ),
    ]
