# Generated by Django 5.2.4 on 2026-08-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_favourites_alter_profile_reads'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='О себе — видно другим пользователям.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shelf_public',
            field=models.BooleanField(default=True, help_text='Могут ли другие пользователи просматривать книжную полку.'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
