# Generated by Django 5.2.4 on 2026-08-20 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_character_edition_moodboardimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Заметка'), ('quote', 'Цитата')], default='note', max_length=10)),
                ('text', models.TextField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Видна ли заметка другим пользователям на публичной полке.')),
                ('has_spoilers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='notes_note_user_id_3f73e0_idx')],
            },
        ),
    ]
