# Generated by Django 5.2.4 on 2026-08-20 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_character_edition_moodboardimage_and_more'),
        ('shelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want', 'Хочу прочитать'), ('reading', 'Читаю'), ('read', 'Прочитано')], default='want', max_length=10)),
                ('is_owned', models.BooleanField(default=False, help_text='Куплено пользователем.')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='books.edition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.DeleteModel(
            name='BookShelf',
        ),
        migrations.AddConstraint(
            model_name='shelfitem',
            constraint=models.UniqueConstraint(fields=('user', 'edition'), name='unique_user_edition_on_shelf'),
        ),
    ]
