# Generated by Django 5.2.4 on 2026-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelfitem_delete_bookshelf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfitem',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
