# Generated by Django 5.2.4 on 2026-08-21 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('min_points', models.PositiveIntegerField(help_text='Сколько очков нужно набрать, чтобы достичь ступени.', unique=True)),
                ('icon', models.CharField(blank=True, help_text='Эмодзи для значка.', max_length=8)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Эмодзи для значка.', max_length=8)),
                ('metric', models.CharField(choices=[('books_read', 'Прочитано книг'), ('reviews_written', 'Написано отзывов'), ('notes_written', 'Оставлено заметок и цитат'), ('genres_explored', 'Освоено жанров'), ('languages_read', 'Языков прочитано')], max_length=20)),
                ('threshold', models.PositiveIntegerField(help_text='Значение метрики, с которого награда выдаётся.')),
                ('points', models.PositiveIntegerField(default=0, help_text='Сколько очков добавляет само получение награды.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'trophies',
                'ordering': ['metric', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.trophy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'trophy'), name='unique_user_trophy')],
            },
        ),
    ]
